/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.gui;

import com.algorithm.AVCAlgo;
import com.algorithm.RC6;
import com.constant.Constant;
import java.io.File;
import java.io.FileOutputStream;
import java.io.ObjectOutputStream;
import javax.swing.JOptionPane;

public class EmbeddedDataForm extends javax.swing.JFrame implements Constant{

    /**
     * Creates new form EmbeddedDataForm
     */
    public EmbeddedDataForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        messageTextArea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        nextButton = new javax.swing.JButton();
        keyText = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Embbeded Data");
        setResizable(false);

        jLabel1.setBackground(new java.awt.Color(255, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Embedded Data Information");
        jLabel1.setToolTipText("");

        jLabel2.setText("Key");
        jLabel2.setToolTipText("");

        messageTextArea.setColumns(20);
        messageTextArea.setRows(5);
        jScrollPane1.setViewportView(messageTextArea);

        jLabel3.setText("Message");
        jLabel3.setToolTipText("");

        nextButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icons/next.png"))); // NOI18N
        nextButton.setText("Next");
        nextButton.setToolTipText("");
        nextButton.setBorderPainted(false);
        nextButton.setContentAreaFilled(false);
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        keyText.setToolTipText("Enter Key");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(64, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(keyText))))
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(nextButton)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(keyText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nextButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
       try {
                String key;
                String message;
                if(!keyText.getText().isEmpty()){
                    key = keyText.getText();
                }else{
                    JOptionPane.showMessageDialog(null, "Please enter key!","Error",JOptionPane.ERROR_MESSAGE);
                    keyText.requestFocus();
                    return;
                }
                if(!messageTextArea.getText().isEmpty()){
                    message = messageTextArea.getText();
                }else{
                    JOptionPane.showMessageDialog(null, "Please enter embbeded data!","Error",JOptionPane.ERROR_MESSAGE);
                    messageTextArea.requestFocus();
                    return;
                }
            if(key.length()!=16){
                JOptionPane.showMessageDialog(null, "Please enter key lenght is 16 character.","ERROR",JOptionPane.ERROR_MESSAGE);
                return;
            }
            System.out.println("Key is : "+key);
            System.out.println("Message is : "+message);
            byte[] embbededKey = key.getBytes();
            System.out.println("Key in bytes : "+embbededKey.length);
            byte[] embbededMessage = message.getBytes();
            System.out.println("Embeded Message :"+embbededMessage.length);
            
            File keyFile = new File(ENCRYPT_FILE_DIRECTORY+DATA_HIDING_KEY);
            FileOutputStream fout = new FileOutputStream(keyFile);
            ObjectOutputStream keyOut = new ObjectOutputStream(fout);
            keyOut.writeObject(embbededKey);
            keyOut.close();
            // encrypt file with embbede message and embbedekey
            byte[] encryptEmbbedeMessage = RC6.encrypt(embbededMessage, embbededKey);
            AVCAlgo.toPrintResult(encryptEmbbedeMessage);
            String avc = AVCAlgo.applyAVCAlgorithm(encryptEmbbedeMessage);
            System.out.println("AVC Algorithm : "+avc);
            File embbeddedMessageFile = new File(ENCRYPT_FILE_DIRECTORY+DATA_HIDING_MESSAGE); 
            FileOutputStream msgFileOutPutStream  = new FileOutputStream(embbeddedMessageFile);
            ObjectOutputStream msgFileObjectStream = new ObjectOutputStream(msgFileOutPutStream);
            msgFileObjectStream.writeObject(avc);
            msgFileObjectStream.close();
            
            JOptionPane.showMessageDialog(null, "Embedded data successfully!..","Message",JOptionPane.INFORMATION_MESSAGE);
            nextButton.setEnabled(false);
        }catch(Exception ex){
            System.out.println("Exception : EmbeddedDataForma.java : "+ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_nextButtonActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPasswordField keyText;
    private javax.swing.JTextArea messageTextArea;
    private javax.swing.JButton nextButton;
    // End of variables declaration//GEN-END:variables
}
